### ISSUE TITLE
Where did you get the .d.ts of simple-git?

### ISSUE THREAD

**Issue by miyatin0212** [benthomasknight/Sleet#1]
Hi. I searched "from 'simple-git'" for getting how to use [simple-git](https://github.com/steveukx/git-js) with TypeScript and found this repository.

After the try-and-error, I couldn't get the auto-completion for simple-git by `import * as simpleGit from 'simple-git'` . Visual Studio Code says "it's type `any` !" whenever...

But cloning this repository, executing `npm install` and opening it by Visual Studio Code, the auto-completion for simple-git works! I compared my project and yours for a while, then noticed that yours has the type definition file ( `.d.ts` ) for simple-git in the project itself. Although getting the reason why yours works, where did you get `simple-git.d.ts` ? Or your wrote this by yourself?

I would appreciate it if you could reply when it is convenient for you.

**Comment by benthomasknight** [comment]
Hey.

I am not 100% sure but I think I got it from [this pull request](https://github.com/steveukx/git-js/pull/163). I do remember it was out of date with what the current functionality is so I have since updated it to fit with how simple-git worked at the time so hopefully it is still valid.

Feel free to use it

**Comment by miyatin0212** [comment]
Thank you for your reply!

I understand where it came from.
After all, simple-git has the `.d.ts` for the promise interface and probably manages it as a component of the library, so I'm using it for now.

But this functionality should be there. I'm asking the owner of simple-git this problem ( https://github.com/steveukx/git-js/issues/256 ), then I want to add this to simple-git if they are waiting for contributing.

When the time comes, I let you know.
